apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: k8s-webapi
          image: sirpeace/k8s-example-webapi
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
          env:
            - name: PORT
              value: "4200"
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: port
            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: database
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  labels:
    app: webapi
spec:
  type: NodePort
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200 # container port?
      nodePort: 31337
